### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by fragmuffin** [fragmuffin/cqparts#24]
Make a logo

### Criteria:

* can be built with `cqparts`
* can be animated (I'm a fan of the simple yet flashy [webpack](https://webpack.github.io/) logo)
* represents what the library does
* as simple as possible, yet distinguishable

I like the idea of the logo being:

* a symbolic representation of what the library does
* a functioning example
* a demonstration of it's potential, (ie: it's animation)
    * export to web-compatible format (something importable by [three.js](https://threejs.org/) and [a-frame](https://aframe.io/))
    * embed animation data (eg: times, transforms, and transition types) in an `Assembly` implementation.

**Comment by fragmuffin** [comment]
1st draft:
![logo](https://user-images.githubusercontent.com/2626190/32940689-783d3f92-cbd7-11e7-853a-fdbd2af7f518.jpg)

using the "A" compass from the `cadquery` logo, to illustrate it's building onto `cadquery`

@dcowden: would you mind if I used the drafter's compass from the `cadquery` logo?

**Problems:**
* The shapes (without surrounding letters) spells "AR", which means nothing
* I want the "R" block to be fastened to "A" with a screw, but that interferes with the "R", and would be very visually cluttered.

**Comment by fragmuffin** [comment]
or something like.
![logo](https://user-images.githubusercontent.com/2626190/32941736-e538ed6e-cbda-11e7-82cf-768f97010b5a.png)

where
* "cq" is a blue cube.
* "parts" is a red rectangular block.
* they're fastened together (perhaps a horizontal bolt through everything)
* animated by removing the bolt, then spinning each block around 360deg, then re-fastening the bolt.

anyway, I'm getting ahead of myself... I'm going to do something more useful now

**Comment by jmwright** [comment]
@fragmuffin The CadQuery logo is in flux right now. The original was made with a logo generator, and there's no real source material available. I've created a [temporary logo](https://github.com/jmwright/cqcad/blob/master/cqcad/content/images/cadquery_logo.svg) for my experimental GUI. I haven't found a font that recreates the hand drawn feel while still being readable yet, so I've just used a generic plain font for now. The main thing I wanted was something that I could use as an application icon or favorite icon on a website, and that's what the compass has ended up being.

**Comment by dcowden** [comment]
I'm ok with anyone using the cq logo, but I really don't like it a lot. I
think maybe I need to figure out a better one.

**Comment by fragmuffin** [comment]
@jmwright @dcowden ok then, I won't base anything off the compass design unless that changes.
I'm liking the flexibility of the blue and red logo above.

When I get around to animating it, I can have the `cadquery` logo on the back of the blue cube, then spin it around briefly to show it, whatever it may be.

**Colour?** (Australian spelling :wink:)
The colours could be anything, they're currently based on the [documentation colours](https://github.com/fragmuffin/cqparts/issues/6#issuecomment-345167140).

Are you inclined to have a base colour for your documentation / logo?...
I ask because it would be good for me to have that colour in my logo... because `cqparts` would be nothing without `cadquery`, so having that reflected in the logo seems apt.

This feels like such a trivial thing to spend time on.
I have to keep reminding myself that it is actually quite important.

**Comment by jmwright** [comment]
On the FreeCAD workbench I just have "CQ" as the icon because I didn't know what else to do at the time. What if the blue box (or whatever color it ends up being and whatever style it's done in) becomes the CadQuery logo? Then projects like cqparts and cqcad can just bolt whatever their red box is onto the CadQuery logo That gives a continuity to the CadQuery ecosystem, but would probably require some logo usage guidelines to be created at some point. Thoughts?

**Comment by dcowden** [comment]
i agree, lets go with something like that cq is a relatively appealing
character combination, as is @fragmuffins' split box logo.

for now lets say the 'official' cq logo is lowercase cq in Roboto bold
font, with a box the same color as the cq docs (#2980B9)

[image: Inline image 1]

or rendered in white with a 2px border
[image: Inline image 2]

**Comment by jmwright** [comment]
@dcowden The images didn't show up in your message.

**Comment by dcowden** [comment]
sorry about that, i guess email pictures dont work...
https://docs.google.com/presentation/d/1pAg2WCOPe6TOGeTenuc5eKMohiGgZfMmJks3BoNYtmE/edit?usp=sharing

**Comment by jmwright** [comment]
That's got a kind-of periodic table vibe to it.

**Comment by dcowden** [comment]
yeah it does-- i thought the same thing. which means we're both the same geek wavelength. but i ended up thinking that was a good thing.  We could consider going all-in on the vibe by making it uppercase C

**Comment by jmwright** [comment]
If we push too far with the periodic table feel, will people get confused and think that CadQuery is a chemistry thing? It could absolutely be used by chemists, but it's a CAD scripting language.

**Comment by dcowden** [comment]
that's a good point. lets stick with this then.

**Comment by jmwright** [comment]
@dcowden Can I go ahead and create vector versions of the light and dark variations of your mockups? I can push them to the CadQuery repo. You can do PNG exports after that if you want, but almost all browsers support direct SVG rendering these days.

@fragmuffin I'm guessing that you're in bed due to the time zone difference, but if you're ok with all of this I'll probably plan on following suit with you on building off the base CQ logo. Let Dave and I know what you think.

**Comment by dcowden** [comment]
@jmwright absolutely feel free!  choose another font if you like it better-- just go with what looks good.

**Comment by jmwright** [comment]
I put the logos in the [doc/_static/logo](https://github.com/dcowden/cadquery/tree/master/doc/_static/logo) directory.

I also included the needed Roboto bold font, and the Apache license that goes with it.

**Comment by jmwright** [comment]
Sorry, that broke the doc build process. The logo materials are [here](https://github.com/dcowden/cadquery/tree/master/logo) now.

**Comment by jmwright** [comment]
Sigh. I'm not sure what's going on. It seems like something's actually changed with travis-sphinx. The nowarn option isn't available anymore or something. I'll figure it out here after bit.

**Comment by fragmuffin** [comment]
Hmm. I'm very confused, the [preview on github](https://github.com/dcowden/cadquery/blob/master/logo/cadquery_logo_dark.svg) looks wrong:
![cadquery_logo_dark](https://user-images.githubusercontent.com/2626190/32975819-99a8d6a4-cc5f-11e7-85c5-949e42df75e0.png) (screenshot)
the off colour is confusing me the most, I have no idea why that would be.

But if I install the font, and view the SVG, it looks correct:
![cadquery_logo_dark_github](https://user-images.githubusercontent.com/2626190/32975818-9971094a-cc5f-11e7-86c4-bd510436f474.png) (also screenshot)

Could you avoid using a font, and convert the font to curves before exporting to svg?
(but still credit the font)

Also, here's the `cqparts` logo now.
![cqparts_logo](https://user-images.githubusercontent.com/2626190/32976042-58e26ec4-cc63-11e7-8172-76881f41a942.png)

but... why am I suddenly so hungry...

![dominos_pizza](https://user-images.githubusercontent.com/2626190/32976044-5d4001a2-cc63-11e7-85fd-375beb05916f.png)

s**t, I may pick another colour ;)

here's some other options.
![logo_spread](https://user-images.githubusercontent.com/2626190/32976476-a347b1fc-cc6a-11e7-823c-30df13ed2d4e.png)
All of these have the same _saturation_ and _value_ as the `cadquery` logo colour `#2980b9`, just the _hue_ is changed.

I like the look of the all blue one, but the colour distinction is not obvious... so I think I'll go for the green (the shade with the `*` on it)

What do you think @jmwright @dcowden ?

**Comment by jmwright** [comment]
Ok, last update. travis-sphinx 2.0.0 was pushed out 6 days ago and broke some things. I've got it fixed now. Here's the final location of the logos.

[doc/_static/logo](https://github.com/dcowden/cadquery/tree/master/doc/_static/logo)

**Comment by jmwright** [comment]
@fragmuffin Here's what the GitHub preview looks like for me.

![screenshot_2017-11-17_22-19-39](https://user-images.githubusercontent.com/1015439/32976521-92d57cee-cbe5-11e7-861a-8c4eadd77a57.png)

I think the logo you've selected with the green looks fine. If you settle on that I'll choose one for cqcad that follows the same pattern but has a different color.

**Comment by fragmuffin** [comment]
@jmwright that fixed the background colour, but I'm still seeing a generic font.
The letters can be easily converted in _inkscape_ by selecting the text then `Path > Object to Path`. This will remove any font requirements of the client.

Now I'm leaning toward:
![cqparts_logo svg_gray](https://user-images.githubusercontent.com/2626190/32977207-c5a14d5a-cc7c-11e7-9712-4a6f2b0ece9a.png)
It looks very nice in the documentation with a dark grey background.

But I still think the red looks good, and I don't care so much that it looks like the dominos logo.
Do you think it's better to have **colour** on the suffixed word `parts` / `cad`... or it doesn't matter

ok, I've officially thought about this too much, and I need to come back to it again later.

**Comment by jmwright** [comment]
Weird, the font renders correctly for me. Do you use Firefox by any chance? Maybe Chrome has the Roboto font built in.

> The letters can be easily converted in inkscape by selecting the text then Path > Object to Path.

Yeah, I was trying to avoid creating something that is harder to modify though. I guess it really doesn't matter. The font and colors are there. If I also document the font size used in Inkscape it's pretty trivial to recreate the logo. I'll try to do that tomorrow.

> Do you think it's better to have colour on the suffixed word parts / cad... or it doesn't matter

I think that colors are fine. We can use colors to differentiate between projects in the CadQuery ecosystem.

**Comment by fragmuffin** [comment]
@jmwright 

> Do you use Firefox by any chance?

I don't habitually, but I do have it (I typically use chrome)
[tries the link in Firefox]
oh yeah!, there it is!... chrome is doing a weird thing

> I was trying to avoid creating something that is harder to modify though

I respect that sentiment, but I think it's going to be quite difficult to get a font to render correctly in an SVG on all clients.
My first google found [this article](https://github.com/JChemPaint/jchempaint/wiki/The-svg-font-problem-and-its-solution), which is a means to embed a font within an SVG... but it apparently doesn't work on Firefox... I find that a little bit funny.

In the long run, I'd love it if I could get `cqparts` to export an svg render... I love it when logos are build with the tools they represent (eg: Matlab).

> I think that colors are fine. We can use colors to differentiate between projects in the CadQuery ecosystem

ok, I think I'll probably go with the red, even though it makes me want pizza.
But I'm still going to sit on it for a few days before I commit to it.

I think it's between these two:
![cqparts_logo](https://user-images.githubusercontent.com/2626190/32978239-371f267c-cc92-11e7-8b6c-954b1faebbc4.png)
![cqparts_logo_grey](https://user-images.githubusercontent.com/2626190/32978262-90b8dd68-cc92-11e7-9909-d58b43ced1b6.png)

**Comment by jmwright** [comment]
@fragmuffin Please try the [logos](https://github.com/dcowden/cadquery/tree/master/doc/_static/logo) now. I converted the text to paths and the saved separate Inkscape files in case we want to tweak the logos later.

**Comment by fragmuffin** [comment]
@jmwright Yep, that's fixed it :+1:

**Comment by fragmuffin** [comment]
@jmwright 
I also just noticed, the background of the light logo is transparent.
So on a light grey background...
![cadquery_logo_spread](https://user-images.githubusercontent.com/2626190/32985495-8f93ef12-cd10-11e7-8ce4-144dab14821f.png)

But in inkscape this isn't obvious.
Alternatively, with a white background it would look like:
![cadquery_alt](https://user-images.githubusercontent.com/2626190/32985514-010d8bee-cd11-11e7-95d9-3c46a138e0d5.png)

I'm not saying the transparency looks bad, I'm just confirming that the transparency is what you intended;
I'm actually quite bad at doing visual fine-tuning. (I'm much more of a "function over form" kind of guy)

**Comment by jmwright** [comment]
@fragmuffin Good catch. I think we should enforce the white background on the light logo. @dcowden thoughts?

**Comment by dcowden** [comment]
yah, i think the white BG is intended. either white bg or blue bg.

**Comment by jmwright** [comment]
Ok, I've fixed the background so that it will always be white.

**Comment by jmwright** [comment]
The dark icon looks pretty nice in the Ubuntu Unity dock.

![screenshot_2017-11-18_22-39-14](https://user-images.githubusercontent.com/1015439/32987207-b4def81a-ccb2-11e7-8a4f-284d16c97968.png)

**Comment by dcowden** [comment]
Yeah that does look nice!
I'm glad we went away from the compass thing

**Comment by fragmuffin** [comment]
Yeah, I'm very pleased with the way it "stacks" with other modules; very clean.

@jmwright the white background looks good, although the [cadquery_logo_light.svg](https://github.com/dcowden/cadquery/blob/master/doc/_static/logo/cadquery_logo_light.svg) image doesn't have the text converted to paths (I'm seeing the old changed font problem)

**Comment by fragmuffin** [comment]
It's also quite easy to CSS style: https://codepen.io/FraggaMuffin/pen/yPpKRp

**Comment by jmwright** [comment]
Sorry, I forgot to convert the text to a path when I saved it as plain SVG. I'll fix it when I'm at a computer later.

**Comment by jmwright** [comment]
I converted the text to paths in the light logo.

**Comment by fragmuffin** [comment]
ok!, I've slept on it now, I'm going with _grey_.

When I build the logo using `cadquery` I'll give the _parts_ block a thread that screws into the _cq_ block. The _grey_ look will go well with the concept of a fastener (which will be one of the more powerful parts of `cqparts`)

**Dark**
![cqparts-dark](https://user-images.githubusercontent.com/2626190/33073202-3b50744a-cf16-11e7-95d6-0f7ff7d3c63b.png)

**Light**
![cqparts-light](https://user-images.githubusercontent.com/2626190/33073204-3c6b5e44-cf16-11e7-99b0-70541222f97e.png)

Thanks for all of your input @jmwright & @dcowden !
